name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag thienlinh1420/chat_app_node
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push Image to Dockerhub
      run: docker push thienlinh1420/chat_app_node
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 188.166.182.237 >> ~/.ssh/known_hosts

    - name: Execute SSH command
      run: |
        ssh -i ~/.ssh/id_rsa root@188.166.182.237
        docker pull thienlinh1420/chat_app_node:latest
        docker stop chat_app_node
        docker rm chat_app_node
        docker run --rm --name chat_app_node -d -p 3000:3000 -e SECRET_KEY=${{ secrets.SECRET_KEY }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} thienlinh1420/chat_app_node
